# Generated by Django 5.1.3 on 2025-05-16 15:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('road', models.CharField(max_length=100, verbose_name='Road')),
                ('house_number', models.CharField(max_length=20, verbose_name='House number')),
                ('lat_lng', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PartyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_title', models.CharField(max_length=100, verbose_name='Party title')),
                ('date', models.DateField(verbose_name='Date')),
                ('creation_day', models.DateField(auto_now_add=True)),
                ('people_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='People')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(16, "You can't invite such young person..")], verbose_name='Age')),
                ('alco', models.BooleanField(verbose_name='Alcohol')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='APP.addressmodel', verbose_name='Address')),
            ],
        ),
    ]
