# Generated by Django 5.1.3 on 2025-09-08 14:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partymodel',
            name='participants',
            field=models.ManyToManyField(related_name='participant_parties', to=settings.AUTH_USER_MODEL),
        ),
    ]
