# Generated by Django 5.1.3 on 2025-07-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partyuser',
            name='avatar',
            field=models.FileField(blank=True, upload_to='<function uploadAvatar at 0x000002CFD49FF9C0>', verbose_name='File'),
        ),
    ]
