# Generated by Django 5.1.3 on 2025-06-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partyuser',
            name='birth',
            field=models.DateField(null=True, verbose_name='birth date'),
        ),
    ]
