# Generated by Django 5.1.3 on 2025-07-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_alter_partyuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partyuser',
            name='avatar',
            field=models.FileField(blank=True, upload_to='users_image/<django.db.models.fields.CharField>', verbose_name='File'),
        ),
    ]
